// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ocean

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OceanClient is the client API for Ocean service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OceanClient interface {
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
}

type oceanClient struct {
	cc grpc.ClientConnInterface
}

func NewOceanClient(cc grpc.ClientConnInterface) OceanClient {
	return &oceanClient{cc}
}

func (c *oceanClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, "/rpc.Ocean/Ask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OceanServer is the server API for Ocean service.
// All implementations must embed UnimplementedOceanServer
// for forward compatibility
type OceanServer interface {
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	mustEmbedUnimplementedOceanServer()
}

// UnimplementedOceanServer must be embedded to have forward compatible implementations.
type UnimplementedOceanServer struct {
}

func (UnimplementedOceanServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedOceanServer) mustEmbedUnimplementedOceanServer() {}

// UnsafeOceanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OceanServer will
// result in compilation errors.
type UnsafeOceanServer interface {
	mustEmbedUnimplementedOceanServer()
}

func RegisterOceanServer(s grpc.ServiceRegistrar, srv OceanServer) {
	s.RegisterService(&Ocean_ServiceDesc, srv)
}

func _Ocean_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OceanServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Ocean/Ask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OceanServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ocean_ServiceDesc is the grpc.ServiceDesc for Ocean service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ocean_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Ocean",
	HandlerType: (*OceanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _Ocean_Ask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/ocean/ocean.proto",
}
